spring:
  application:
    name: jinrouwerewolf
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/jinrouwerewolf?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      # 地址
      host: 127.0.0.1
      # 端口号
      port: 6379
      # 数据库索引（默认为0）
      database: 0
      # 连接超时时间（毫秒）
      timeout: 1800000
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 20
          # 最大阻塞等待时间（负数表示没有限制）
          max-wait: -1
          # 连接池中最大空闲连接
          max-idle: 5
          # 连接池中最小空闲连接
          min-idle: 0
# mvc:
#   static-path-pattern: /resources/**

# token过期时间，通过redis完成 单位秒
token:
  expire: 604800   #60*60*24*7

web:
  resources:
    static-locations: classpath:/static/, classpath:/public/, classpath:/templates/

mybatis-plus:
  type-handlers-package: com.jinrou.jinrouwerewolf.TypeHandler
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
  servlet:
    session:
      timeout: 0s  # 设置 session 超时为 0，表示禁用 session
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket.messaging: DEBUG
    org.mybatis: DEBUG
    com.baomidou.mybatisplus: DEBUG
    org.apache.ibatis.type.TypeHandlerRegistry: DEBUG



