package com.jinrou.jinrouwerewolf.util;

public interface ConstConfig {
    /**
     * 游戏状态码
     */
    String GAME_START_FROM_SERVER = "GAME_START_FROM_SERVER"; //成功开始游戏，告知所有玩家游戏开始
    String GAME_STATUS_ISOVER = "GAME_STATUS_ISOVER"; //服务端发送 定胜负
    String GAME_STATUS_OVER_MURABITO_WIN = "GAME_STATUS_OVER_MURABITO_WIN";  //村人胜利
    String GAME_STATUS_OVER_WEREWOLF_WIN = "GAME_STATUS_OVER_WEREWOLF_WIN";  //人狼胜利
    String GAME_STATUS_OVER_KITSUNE_WIN = "GAME_STATUS_OVER_KITSUNE_WIN";  //妖狐胜利
    String GAME_STATUS_NOT_END = "GAME_STATUS_NOT_END"; //未结束
    String GAME_STATUS_OVER_TIE = "GAME_STATUS_OVER_TIE"; //平局
    String GAME_STATUS_NOT_OVER_TIE = "GAME_STATUS_NOT_OVER_TIE"; //平票

    /**
     * 游戏消息码
     */
    String GAME_MESSAGE_SYSTEM = "GAME_MESSAGE_SYSTEM";  //系统信息 等同月下灰色公频内容
    String GAME_MESSAGE_TALK = "GAME_MESSAGE_TALK"; //玩家发言
    String GAME_MESSAGE_SYSTEM_VOTELIST = "GAME_MESSAGE_SYSTEM_VOTELIST";  //公示投票情况
    String GAME_REQUEST_VOTE = "GAME_REQUEST_VOTE"; //玩家投票
    String GAME_REQUEST_URANAI = "GAME_REQUEST_URANAI"; //占卜请求
    String GAME_REQUEST_REIBAI = "GAME_REQUEST_REIBAI"; //灵能者请求(暂时没用
    String GAME_REQUEST_KARIUDO = "GAME_REQUEST_KARIUDO"; //猎人守护请求
    String GAME_REQUEST_JINROU = "GAME_REQUEST_JINROU"; //人狼咬人请求

    /**
     * 房间层面
     */
    String ROOM_REQUEST_START_FROM_OWNER = "ROOM_REQUEST_START_FROM_OWNER"; //房主开始游戏请求
    String ROOM_REQUEST_READY_FROM_PLAYER = "ROOM_REQUEST_READY_FROM_PLAYER";  //玩家准备
    String ROOM_STATE_ALREADY_FULL = "ROOM_STATE_ALREADY_FULL"; //服务器返回给加入者：房间已满
    String ROOM_NOT_ENOUGH_NUM = "ROOM_NOT_ENOUGH_NUM"; //服务器返回给房主：房间人数不够（只有房主等情况
    String ROOM_NOT_ALL_READY = "ROOM_NOT_ALL_READY"; //服务器返回给房主：房间未全部准备
    String ROOM_GAME_START = "ROOM_GAME_START"; //游戏开始
    String ROOM_SOMEONE_JOIN_ROOM = "ROOM_SOMEONE_JOIN_ROOM"; //有人加入房间
    String ROOM_SOMEONE_LEFT_ROOM = "ROOM_SOMEONE_LEFT_ROOM"; //有人离开
    String ROOM_GAMESETTINGS_CHANGE = "ROOM_GAMESETTINGS_CHANGE"; //设置更新
    String ROOM_INITIAL = "ROOM_INITIAL"; //房间初始化
    String ROOM_SOMEONE_READY = "ROOM_SOMEONE_READY"; //房间初始化
    String GAME_STATUS_DAY = "GAME_STATUS_DAY";
    String GAME_STATUS_DAY_END = "GAME_STATUS_DAY_END";
    String GAME_STATUS_NIGHT = "GAME_STATUS_NIGHT";
    String GAME_STATUS_MORNING = "GAME_STATUS_MORNING";
    String GAME_STATUS_VOTE = "GAME_STATUS_VOTE";
    String GAME_STATUS_BEFORE_START = "GAME_STATUS_BEFORE_START";
    String GAME_STATUS_IS_OVER = "GAME_STATUS_IS_OVER";
    String GAME_STATUS_IS_DESTROYED = "GAME_STATUS_IS_DESTROYED";
    String GAME_SELF_IDENTITY = "GAME_SELF_IDENTITY";

    String GAME_VOTE_INFO_BODY = "GAME_VOTE_INFO_BODY";
    String GAME_VOTE_INFO_RESULT = "GAME_VOTE_INFO_RESULT";
    String GAME_ACTION_URANAI = "GAME_ACTION_URANAI";
    String GAME_ACTION_VOTE = "GAME_ACTION_VOTE";
    String GAME_ACTION_KARIUDO = "GAME_ACTION_KARIUDO";
    String GAME_ACTION_KAMI = "GAME_ACTION_KAMI";
    String GAME_NIGHT_DIE = "GAME_NIGHT_DIE";
    String GAME_SUSPEND_TIME = "GAME_SUSPEND_TIME";
    String GAME_URANAI_RESULT = "GAME_URANAI_RESULT";
    String GAME_REIBAI_RESULT = "GAME_REIBAI_RESULT";
    String GAME_KARIUDO_RESULT = "GAME_KARIUDO_RESULT";
    String GAME_WOLF_HAS_KAMI = "GAME_WOLF_HAS_KAMI";
    String GAME_ACTION_GM_TIME_LONG = "GAME_ACTION_GM_TIME_LONG";
    String GAME_ACTION_GM_TIME_SHORT = "GAME_ACTION_GM_TIME_SHORT";
    String GAME_STATUS_SILENT = "GAME_STATUS_SILENT";
    String ROOM_DISCARDED = "ROOM_DISCARDED";
    String ROOM_PLAYER_KICKED = "ROOM_PLAYER_KICKED";
    String GAME_GM_KILL = "GAME_GM_KILL";
    String GAME_GM_REVIVE = "GAME_GM_REVIVE";

}
